import React from 'react'
import { motion } from 'framer-motion'
import { FiPlay } from 'react-icons/fi'

const ProductPreview = () => {
  // Animation Variants
  const sectionVariants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.8, ease: 'easeOut' }
    }
  }

  const leftContentVariants = {
    hidden: { opacity: 0, x: -50 },
    visible: {
      opacity: 1,
      x: 0,
      transition: { duration: 0.8, type: 'spring', stiffness: 100, damping: 15 }
    }
  }

  const rightContentVariants = {
    hidden: { opacity: 0, x: 50 },
    visible: {
      opacity: 1,
      x: 0,
      transition: { duration: 0.8, type: 'spring', stiffness: 100, damping: 15 }
    }
  }

  const bulletListVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.2 }
    }
  }

  const bulletItemVariants = {
    hidden: { opacity: 0, x: -20 },
    visible: {
      opacity: 1,
      x: 0,
      transition: { duration: 0.5 }
    }
  }

  const cardContainerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.15, delayChildren: 0.2 }
    }
  }

  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { type: 'spring', stiffness: 100, damping: 15 }
    }
  }

  return (
    <section id="product-preview" className="relative section-padding overflow-hidden" style={{
      background: '  linear-gradient(335deg,rgba(223, 224, 240, 1) 2%, rgba(196, 205, 242, 1) 51%, rgba(242, 245, 255, 1) 100%)'
    }}>
      <div className="container-custom">
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          variants={sectionVariants}
          className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center"
        >
          {/* Left - Text Content */}
          <motion.div
            variants={leftContentVariants}
            className="order-2 lg:order-1"
          >
            <h2 className="font-cinzel text-3xl md:text-4xl lg:text-5xl font-bold text-text-dark mb-6 leading-tight">
              See NEWS AI in Action
            </h2>
            <p className="text-lg text-text-secondary leading-relaxed mb-8">
              Get a glimpse of your personalized AI Daily Brief. Every morning, receive key insights tailored to your interests, curated from thousands of trusted sources.
            </p>

            {/* Sample Brief Content */}
            <div className="backdrop-blur-md bg-white/60 border border-white/80 rounded-2xl p-6 shadow-xl mb-6">
              <h3 className="font-semibold text-xl text-text-dark mb-4">
                AI Daily Brief – Today's Key Insights
              </h3>
              <motion.ul
                variants={bulletListVariants}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                className="space-y-3"
              >
                <motion.li variants={bulletItemVariants} className="flex items-start gap-3">
                  <span className="flex-shrink-0 w-2 h-2 rounded-full bg-brand-blue mt-2"></span>
                  <span className="text-base text-text-secondary">
                    Technology stocks surge as AI breakthrough announced
                  </span>
                </motion.li>
                <motion.li variants={bulletItemVariants} className="flex items-start gap-3">
                  <span className="flex-shrink-0 w-2 h-2 rounded-full bg-brand-blue mt-2"></span>
                  <span className="text-base text-text-secondary">
                    Global climate summit reaches historic agreement
                  </span>
                </motion.li>
                <motion.li variants={bulletItemVariants} className="flex items-start gap-3">
                  <span className="flex-shrink-0 w-2 h-2 rounded-full bg-brand-blue mt-2"></span>
                  <span className="text-base text-text-secondary">
                    Healthcare innovation leads to breakthrough in gene therapy
                  </span>
                </motion.li>
              </motion.ul>
            </div>

            <p className="text-sm text-text-secondary italic">
              This is a sample brief generated by NEWS AI. Your brief adapts to your topics and interests.
            </p>
          </motion.div>

          {/* Right - Dashboard Preview */}
          <motion.div
            variants={rightContentVariants}
            className="order-1 lg:order-2"
          >
            <motion.div
              whileHover={{ scale: 1.02 }}
              className="relative backdrop-blur-md bg-white/40 border border-white/50 rounded-3xl p-8 shadow-2xl"
            >
              {/* Mock Dashboard Header */}
              <div className="flex items-center justify-between mb-6 pb-4 border-b border-gray-200">
                <h4 className="font-cinzel text-xl font-bold text-text-dark">
                  Your Dashboard
                </h4>
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-green-500"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                  <div className="w-3 h-3 rounded-full bg-red-500"></div>
                </div>
              </div>

              {/* Mock News Cards */}
              <motion.div
                variants={cardContainerVariants}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                className="space-y-4"
              >
                {/* Card 1 */}
                <motion.div
                  variants={cardVariants}
                  whileHover={{ scale: 1.03, y: -5 }}
                  className="bg-white/80 rounded-xl p-4 shadow-md"
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs font-semibold rounded">
                      Technology
                    </span>
                    <span className="text-xs text-text-secondary">5 min ago</span>
                  </div>
                  <h5 className="font-semibold text-base text-text-dark mb-2">
                    AI Revolutionizes Market Analysis
                  </h5>
                  <p className="text-sm text-text-secondary line-clamp-2">
                    Advanced algorithms are transforming how investors analyze market trends...
                  </p>
                </motion.div>

                {/* Card 2 */}
                <motion.div
                  variants={cardVariants}
                  whileHover={{ scale: 1.03, y: -5 }}
                  className="bg-white/80 rounded-xl p-4 shadow-md"
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-semibold rounded">
                      Finance
                    </span>
                    <span className="text-xs text-text-secondary">12 min ago</span>
                  </div>
                  <h5 className="font-semibold text-base text-text-dark mb-2">
                    Crypto Markets Show Strong Recovery
                  </h5>
                  <p className="text-sm text-text-secondary line-clamp-2">
                    Major cryptocurrencies rally as institutional adoption continues...
                  </p>
                </motion.div>

                {/* Card 3 */}
                <motion.div
                  variants={cardVariants}
                  whileHover={{ scale: 1.03, y: -5 }}
                  className="bg-white/80 rounded-xl p-4 shadow-md"
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className="px-2 py-1 bg-sky-100 text-sky-700 text-xs font-semibold rounded">
                      World News
                    </span>
                    <span className="text-xs text-text-secondary">18 min ago</span>
                  </div>
                  <h5 className="font-semibold text-base text-text-dark mb-2">
                    Global Summit Addresses Climate Change
                  </h5>
                  <p className="text-sm text-text-secondary line-clamp-2">
                    Leaders from 150 countries commit to ambitious new targets...
                  </p>
                </motion.div>
              </motion.div>

              {/* Play Button Overlay */}
              <motion.div
                whileHover={{ scale: 1.1 }}
                className="absolute inset-0 flex items-center justify-center bg-black/10 rounded-3xl backdrop-blur-[2px] opacity-0 hover:opacity-100 transition-opacity duration-300 cursor-pointer group"
              >
                <div className="w-16 h-16 rounded-full bg-brand-blue flex items-center justify-center shadow-2xl">
                  <FiPlay className="w-8 h-8 text-white ml-1" />
                </div>
              </motion.div>
            </motion.div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  )
}

export default ProductPreview
